### ISSUE TITLE
Previous page

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#10]
I had the case of an action performed in a webapp made with mail email provider that sent me to a page without being able to exit it : it would be desirable to have a key in each webapp 
        **  previous page **

**Comment by gbdomubpkm** [comment]
I also think that a page reload button would be useful in case the page is not loaded properly: network occasionally weak...

**Comment by timsueberkrueb** [comment]
Webber uses the standard `webapp-container` which supports those features :+1: I will make them accessible.

**Comment by timsueberkrueb** [comment]
Done.
