### ISSUE TITLE
Help links in Webber

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#14]
Make sure that help links in webber remain confined in the application (patterns) or open in private and non-conventional windows ?

**Comment by timsueberkrueb** [comment]
Why? Could you explain your motivation for this?

**Comment by gbdomubpkm** [comment]
My point of view is this: since the application is described as confined, the idea is to keep everything confined, including the help links. Or at least leave as few traces as possible (private windows). It is true that personally, I prefer to navigate in private windows. Does that make (a little) sense?

**Comment by timsueberkrueb** [comment]
I think ideally this is would be a feature in Morph. I don't think it's worth the effort to create a webview inside the Webber app just to enable this. By adding this option to Morph it solves this problem for you for all apps that open external links. See #13.
