### ISSUE TITLE
Sreenshot lost

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#15]
When sharing an internet link with Webber to create a webapp : when we navigate for the icon between default, screenshot, custom before confirmation of creating a webapp, the screenshot is lost (square becomes grey). The screenshot is also lost if we try to change the name in properties.

There is a workaround : when we paste an internet link into webber to create a webapp, the screenshot is not lost even by changing the name of the webapp.

**Comment by timsueberkrueb** [comment]
Thanks for reporting! Will look into this.

**Comment by timsueberkrueb** [comment]
Hmm ... couldn't reproducing this, yet. Do you have a site where this occurs consistently?

**Comment by gbdomubpkm** [comment]
https://www.lequipe.fr/Tennis/   for example, on stable channel on BQ E5 HD.

On the other hand, since this morning, the webber app seems not to work anymore on the dev channel (on OPO). The app doesn't launch anymore, as the wheel keeps spinning.
And for you

**Comment by timsueberkrueb** [comment]
Interesting. Could you provide a log for the crash? E.g. provide `cat ~/.cache/upstart/application-click-webber.timsueberkrueb_webber_0.4.0.log` via https://paste.ubuntu.com.

**Comment by gbdomubpkm** [comment]
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'

Creating a QMirClientScreen now

QQmlApplicationEngine failed to load component

qrc:/qml/Main.qml:30 Type MainPage unavailable

qrc:/qml/MainPage.qml:26 Type Label unavailable

file:///usr/lib/arm-linux-gnueabihf/qt5/qml/QtQuick/Controls.2/Suru/Label.qml:-1 No such file or directory

**Comment by timsueberkrueb** [comment]
Thanks! Can you also provide the output of `ls /usr/lib/arm-linux-gnueabihf/qt5/qml/QtQuick/Controls.2/Suru`.

**Comment by gbdomubpkm** [comment]
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/QtQuick/Controls.2/Suru/qmldir

file:///usr/lib/arm-linux-gnueabihf/qt5/qml/QtQuick/Controls.2/Suru/libqtquickcontrols2surustyleplugin.so

**Comment by gbdomubpkm** [comment]
you want the contents of the files?

**Comment by timsueberkrueb** [comment]
No, thanks! Looks like something is wrong with the qqc2-suru-style package on the dev channel.

**Comment by timsueberkrueb** [comment]
Package build 15 from January 24th seemingly has produced the broken package: https://ci.ubports.com/job/qqc2-suru-style/job/xenial/15/
