### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by ernesst** [timsueberkrueb/webber#16]
Hello, 
would it be possible to create an arm64 version ? 

Thanks

**Comment by timsueberkrueb** [comment]
Yes, will do as soon as someone (including  me :P) gets the clickable Rust plugin to build for arm64 :)

**Comment by timsueberkrueb** [comment]
Good news! The fabulous @jonnius got it working!
@MichaelTunnell, @ernesst  do you happen do have an arm64 device at hand for testing?
Here is a [`.click` for v0.5.1](https://github.com/timsueberkrueb/webber/releases/download/v0.5.1/webber.timsueberkrueb_0.5.1_armhf.click).

I have no arm64 device for testing, yet.

**Comment by jonnius** [comment]
Thanks for the flowers. I hand them over to @extraymond who found the workaround.

**Comment by ernesst** [comment]
Seems somewhat working, but got stuck on creating the shortcut : 
http://paste.ubuntu.com/p/MdfCMztTfS/

**Comment by MichaelTunnell** [comment]
unfortunately my UT phone is OnePlus 1 so I cant test this. I know someone with a pinephone so I will ask them to test it. They are the person who informed me of it not working for them so hopefully they can test it

**Comment by timsueberkrueb** [comment]
Thanks a lot for testing @ernesst. I'm sorry, I forgot to adjust the prebuild script. I have attached [a new click](https://github.com/timsueberkrueb/webber/releases/download/v0.5.1/webber.timsueberkrueb_0.5.1_arm64.click).

@MichaelTunnell that would be great, thank you!

**Comment by ernesst** [comment]
It works thanks.

**Comment by timsueberkrueb** [comment]
`v0.5.2` with arm64 support has just been released to the Open Store. Let me know if you encounter any issues. Thank you.
