### ISSUE TITLE
Several webapps of the same website possible ?

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#17]
Hello.
An idea I've had in my head for a long time but it hasn't been formalized.
Would it be possible to make several webapps from the same website but opening on different pages.
Let me explain : at the moment, if I make a webapp about morph-browser then following a webapp about webber, the webapp about webber overwrites the webapp about morph.
So, I think it's impossible to have two github webapps currently.
What do you think of this idea ?
Thank you !

**Comment by timsueberkrueb** [comment]
Yeah, technically, that's definitely possible (we can just use different app names in the manifest). But what's the use case for having two web apps for the same site?

**Comment by gbdomubpkm** [comment]
To buy some time.
My example from above, a bit of a bookmark use.
If it's not too costly in work, in my opinion, this feature should be offered to the user who can use it in his own way, or not use it at all.

**Comment by timsueberkrueb** [comment]
Done.
