### ISSUE TITLE
activate a webapp in computer mode

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#18]
Is it possible to implement this parameter as in morph-browser?

**Comment by timsueberkrueb** [comment]
Hey, yeah, this seems to be possible without any changes to Morph by setting the `--user-agent-string=USER_AGENT` flag to a desktop browser's user agent (http://docs.ubports.com/en/latest/appdev/webapp/guide.html).
Webber could have an option for this.

**Comment by timsueberkrueb** [comment]
Done.
