### ISSUE TITLE
Can't launch a webapp created from webber 0.5.0

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#19]
Webapps created from webber 0.5.0 install but do not launch ! Pressing the webapp icon has no effect!

I noticed that after installing a webapp, for the webapp
cache =0 config =0 Data =0
I don't know if that's normal.
Sorry!

**Comment by gbdomubpkm** [comment]
For stable channel..

**Comment by timsueberkrueb** [comment]
Yikes! Could you share which site(s) you experience this problem with? It is working for me on Nexus 5 dev for all sites I have tested.

**Comment by gbdomubpkm** [comment]
Hello.

The faulty package is fixed in dev. Webber 0.5.0 launches now.

I've done different tests with v 0.5.0.
Problems in my tests with some sites.
. on the stable channel (bq E5 HD)
https://www.lequipe.fr/Tennis/ blocking without launching the site

. on the dev channel (OPO)
it seems impossible to create two functional webapps of the site www.lequipe.fr (different pages). I got a phone block.

another case: webapp https://fr.tennistemple.com/ works but if I want to make a webapp of a particular mach, for example https://fr.tennistemple.com/open-daustralie-2020-t4474/fucsovics-federer-m4063929/discussions , the webapp seems to be created but crashes.

Note that with github, I was able to create two different webapps with different pages that work.

**Comment by timsueberkrueb** [comment]
Thanks a lot, will check what's going wrong.

**Comment by timsueberkrueb** [comment]
Fixed. Sorry for this!

**Comment by gbdomubpkm** [comment]
I've checked every case I've presented. Everything works NICKEL now.
Great job. Thank you. 👍

**Comment by gbdomubpkm** [comment]
Please, can ou try to create a webapp with
https://web.telegram.org/#/login
on STABLE channel.
It doesn't work for me on stable with bq E5 HD  wheareas it's work on devel with OPO !!
Thank you

**Comment by gbdomubpkm** [comment]
I installed the .click of the OPO dev on the BQ stable : the result is the same: the icon doesn't respond.
Then I went to UTTT and I noticed that on the bq cache= 0 config = 0 data = 0 whereas on the OPO it's not the case : cache= something config= sth data= sth.

**Comment by timsueberkrueb** [comment]
Did it work on stable before v0.5.0?

**Comment by gbdomubpkm** [comment]
I didn't try before but i reinstalled Webber 0.4.0 and Yes !!! It's work !! 👍
What a lot of special cases! 😉

**Comment by timsueberkrueb** [comment]
Oh no, I have a suspicion what could be going wrong.
Could you send me the logfile (`~/.cache/upstart/application-click-<name>.webber`) where `<name>` is a name generated by Webber for the shortcut, e.g via https://paste.ubuntu.com?

**Comment by gbdomubpkm** [comment]
Webapp telegram with Webber 0.4.0 after pressing the icon :

http://paste.ubuntu.com/p/gnxFKfJtHc/

**Comment by timsueberkrueb** [comment]
Thanks! Could you provide the log of the v0.5.0 version?

**Comment by gbdomubpkm** [comment]
Here is the log for Webber v0 5.1 for OPO dev :
http://paste.ubuntu.com/p/MpTqhV2c3P/

No log for Webber  v 0.5.1 on Bq stable as the telegram webapp doesn't launch (icon inactive).

**Comment by timsueberkrueb** [comment]
Should be fixed in `v0.5.2`, thank you for reporting!
