### ISSUE TITLE
access problem to options with webapp of a mail provider

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#20]
Hello.
Since I don't know the nature of the problem, I'm submitting the case to you.
With  https://www-2.mailo.com

Internet Mail provider: 'log out' option visible (se déconnecter)
![website se déconnecter visible](https://user-images.githubusercontent.com/50362604/73595636-30009700-451b-11ea-8870-1926014bb8a9.png)

webapp built with webber : hidden 'logout' option
![Se déconnecter caché](https://user-images.githubusercontent.com/50362604/73595698-ea909980-451b-11ea-8a2e-122af8cc91f0.png)

Internet Mail provider: option 'send mail' visible (envoyer)
![website envoyer visible](https://user-images.githubusercontent.com/50362604/73595756-6854a500-451c-11ea-92f3-73ee367af605.png)
webapp built with webber : option 'send mail' hidden by the keyboard

![Option envoyer cachée](https://user-images.githubusercontent.com/50362604/73595805-c5e8f180-451c-11ea-87cb-86e53490b246.png)

You can see the option by transparency. If I lower the keyboard, the option remains hidden.

The workaround to be able to reach and use the hidden options with the webapp is to zoom the webapp to 145%
where do you think the problem lies?
Thank you

**Comment by timsueberkrueb** [comment]
Which options have you selected when creating the app, e.g. fullscreen, header bar ...?

**Comment by gbdomubpkm** [comment]
Indeed, I tried all the options, created the .clicks and the 'problem' actually occurs when I activate the option: show title bar (wih/back forward options).  The title bar shifts the options down the width of this bar I think. So it's probably normal behavior unless you can do something about it.

**Comment by timsueberkrueb** [comment]
In that case, I am afraid, I'm pretty sure this is the website's fault. Sorry, there's nothing I can do about that.

**Comment by gbdomubpkm** [comment]
It's not essential.
I know that if you could have, you would have!
Thank you for thinking about it.
