### ISSUE TITLE
Feature Request: Bottom Navigation

### ISSUE THREAD

**Issue by Pdbrantley** [timsueberkrueb/webber#21]
This is a feature request for the ability to add bottom navigation to created web apps. It seems that many web apps function and look best in fullscreen containers without top bars, however many apps require at least basic forward and back navigation. It would be nice if the option could be added to include some type of bottom navigation when creating a webapp.

**Comment by timsueberkrueb** [comment]
Hey, I love ogra's alternative webapp-container and its bottom navigation!
Unfortunately, If I wanted to support this in webber today, I would need to generate QML source code for shortcuts that want to use this style of navigation.
I really do not want to go this route. Webber currently produces lightweight shortcuts which basically only consist of a desktop file and some metadata around it.

Is there any chance we can convince [the folks building the official webapp container](https://github.com/ubports/morph-browser) to support ogra's bottom navigation as additional command line arguments?
