### ISSUE TITLE
Internationalization of Webber

### ISSUE THREAD

**Issue by Anne017** [timsueberkrueb/webber#23]
I would like to contribute to Webber translation in French.
Would it be possible to activate internationalization using the text: i18n.tr("...") structure in all QML files?
Thanks!

**Comment by timsueberkrueb** [comment]
Hey, thanks for reminding me.
I'm working on it.

**Comment by timsueberkrueb** [comment]
@Anne017 I've now implemented translation support. Let me know if you encounter any issues or non-translatable strings!

**Comment by Anne017** [comment]
Thanks a lot!
Seems OK now, see French translation proposal in #25 .
