### ISSUE TITLE
Links open in Onion browser

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#26]
Something strange : Links included in a webapp built with webber open in onion-browser (if installed)  and not morph-browser !

**Comment by timsueberkrueb** [comment]
I can't reproduce this with Onion browser 0.3 on Nexus 5 RC, build 2020-W28 (20200708).

**Comment by gbdomubpkm** [comment]
I had uninstalled Onion the moment I opened the issue. Having very recently reinstalled Onion, indeed, the problem doesn't seem to be there now. I close.

**Comment by timsueberkrueb** [comment]
Glad to hear it's fixed!
