### ISSUE TITLE
Unable to create a webapp

### ISSUE THREAD

**Issue by stanwood77** [timsueberkrueb/webber#28]
Hi 
I'm unable to create a webapp with www.meteosuisse.ch
When installing the clickpackage I get the error: "Verify it's a valid click package"
(Please refer to original error messages in attachment).
Thank you for your help.
![screenshot20200524_001249735](https://user-images.githubusercontent.com/62994815/82741562-b30c5e00-9d53-11ea-9161-c1d1cd5d099f.png)
![screenshot20200524_000520544](https://user-images.githubusercontent.com/62994815/82741563-b43d8b00-9d53-11ea-9b8a-1df9340768e0.png)

**Comment by timsueberkrueb** [comment]
Hey, https://www.meteosuisse.ch/ seems to have a certificate issue. I think https://www.meteosuisse.admin.ch/ or http://www.meteosuisse.ch/ should work.

**Comment by stanwood77** [comment]
Great. It works fine. 👍Thank you very much. 
Advices for other users: Don’t put any accent on letters in the webapp title when using another language. I.e. Replace «Météosuisse » with « MeteoSuisse » in order to enable the installation of the .click package though OpenStore.
