### ISSUE TITLE
App immediately closes

### ISSUE THREAD

**Issue by BigB84** [timsueberkrueb/webber#30]
Hello,

**I'm on nexus 5 Ubuntu Touch, RC channel.**
I used Webber to create and install some webapps.
After I click the icon, app starts but then it closes and I'm back to home screen.
I don't have this problem with Web App Creator apps from OpenStore.

_(If You want me to send logs, could You please write me instructions? :))_

**Comment by timsueberkrueb** [comment]
Hey @BigB84, thanks for reporting an issue.
Could you send me the url of one of the sites where this happens? I will check if I can reproduce it. Also please make sure that you have the latest version of Webber installed.

**Comment by BigB84** [comment]
Of course, may be https://meet.jit.si/

I use webber 0.5.4

**Comment by timsueberkrueb** [comment]
Interesting, it worked on my Nexus 5 RC (build 20200507) for me when I tested it just now.
Did you configure any options? Otherwise, I guess I need to try it on a newer RC build.

**Comment by timsueberkrueb** [comment]
Apparently, there is no newer RC build for the Nexus 5. What build are you on?

**Comment by BigB84** [comment]
I'm on 2020-W19

**Comment by timsueberkrueb** [comment]
Can you please delete the app using the Open Store, recreate it with the default options and send me `~/.cache/upstart/application-click-meet-jit-si.webber_meet-jit-si_1.0.0.log` in case the problem persists?

**Comment by BigB84** [comment]
OK, so problem was - special permissions in Webber. Jitsi created on default options, worked after asking for necessary permissions :).

Anyway here is the log:
`Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
Creating a QMirClientScreen now
Setting session cookie mode to "restored"
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
qml: Loading webview on /home/phablet/.local/share/meet-jit-si.webber
QQmlExpression: Expression file:///usr/share/morph-browser/webcontainer/WebApp.qml:486:25 depends on non-NOTIFYable properties:
    unity::action::qml::ActionManager::globalContext
WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
Sandboxing disabled by user.
shm_open() failed: Permission denied
qq= WebViewImplOxide_QMLTYPE_94(0xa91678) 0xb35890
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebView.qml:138:5: QML Connections: Cannot assign to non-existent property "onContextMenuIntercepted"
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebView.qml:138:5: QML Connections: Cannot assign to non-existent property "onInsertionHandleTapped"
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebView.qml:138:5: QML Connections: Cannot assign to non-existent property "onStatusChanged"
[0615/234012:ERROR:address_tracker_linux.cc(172)] Could not bind NETLINK socket: Address already in use
shm_open() failed: Permission denied

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/UnityWebApps/UnityWebAppsUtils.js:95: TypeError: Property 'addUserScript' of object MorphWebContext_QMLTYPE_2(0xb35420) is not a function
qml: Start browsing
UnityWebappsAppModel::data: Invalid index (out of bound)
QDir::mkpath: Empty or null file name
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebView.qml:139:17: Unable to assign [undefined] to QObject*
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.122\" (uid=32011 pid=16420 comm=\"webapp-container --webappUrlPatterns=https?://meet\") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3576 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.122\" (uid=32011 pid=16420 comm=\"webapp-container --webappUrlPatterns=https?://meet\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3576 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.122\" (uid=32011 pid=16420 comm=\"webapp-container --webappUrlPatterns=https?://meet\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3576 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.122\" (uid=32011 pid=16420 comm=\"webapp-container --webappUrlPatterns=https?://meet\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3576 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
[16420:16496:0615/234013.037707:ERROR:nss_util.cc(83)] Failed to create /home/phablet/.pki/nssdb directory.
[16420:16496:0615/234013.037939:ERROR:nss_util.cc(727)] After loading Root Certs, loaded==false: NSS error code: -8018
[16420:16494:0615/234013.059802:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 16559: Permission denied (13)

(process:16420): dconf-CRITICAL **: unable to create file '/run/user/32011/dconf/user': Permission denied.  dconf will not work properly.
qml: Loaded 14 UA override(s) from file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/ua-overrides-mobile.js
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Morph/Web/MorphWebContext.qml:100: Error: Invalid write to global property "userAgentOverrides"
[16420:16494:0615/234013.396642:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 16577: Permission denied (13)
qml: [JS] (https://meet.jit.si/:24) (TIME) index.html loaded:	
qml: [JS] (https://meet.jit.si/:0) Failed to load https://web-cdn.jitsi.net/meetjitsi_4180.838/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://meet.jit.si' is therefore not allowed access. The response had HTTP status code 403.
qml: [JS] (https://meet.jit.si/?rCounter=1:24) (TIME) index.html loaded:	
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:17.167Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:19.753Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:19.982Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:20.098Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:20.102Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:20.170Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:20.178Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:20.182Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:20.192Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:20.241Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:110) [Amplitude] WARNING: Property key "conference_name" with invalid value type undefined, ignoring
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:20.666Z
[PERFORMANCE]: Last frame took 119 ms to render.
shm_open() failed: Permission denied
shm_open() failed: Permission denied
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:21.984Z
Data set on unsupported clipboard mode. QMimeData object will be deleted.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:42.768Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:42.771Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:42.785Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:42.792Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:42.823Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:110) [Amplitude] WARNING: Property key "conference_name" with invalid value type undefined, ignoring
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:42.844Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:42.996Z
qml: [JS] (https://meet.jit.si/Lalalalaldog:24) (TIME) index.html loaded:	
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:43.332Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:45.664Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:45.980Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:45.982Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:46.032Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:46.039Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:46.046Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:46.054Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:46.113Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:46.347Z
shm_open() failed: Permission denied
[PERFORMANCE]: Last frame took 93 ms to render.
shm_open() failed: Permission denied
[PERFORMANCE]: Last frame took 44 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:47.892Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:50.556Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:50.562Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:50.568Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:50.575Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:50.648Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:51.044Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:40:51.081Z
[PERFORMANCE]: Last frame took 50 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:40:54.965Z
[PERFORMANCE]: Last frame took 53 ms to render.
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(124.87,486.261) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(284.87,304) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(92.5217,461.913) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(296.696,347.826) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(278.957,313.043) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(245.565,339.478) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(247.304,500.87) id:2000002 timeHeld:0)
TouchPointPressed without previous release event QQuickEventPoint(valid:true accepted:false state:Pressed scenePos:QPointF(257.391,544) id:2000002 timeHeld:0)
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.213Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:28.337Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.384Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.453Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.512Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.516Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.637Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:28.642Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.645Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:28.645Z
qml: 'caller' is DEPRECATED. It has no effect.
[PERFORMANCE]: Last frame took 154 ms to render.
[PERFORMANCE]: Last frame took 102 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:33.736Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:33.739Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:33.741Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:33.742Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:33.746Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:34.339Z
[16420:16496:0615/234135.928126:ERROR:user_input_monitor_linux.cc(130)] Couldn't open X display
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:35.933Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:35.938Z
shm_open() failed: Permission denied
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:36.173Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.209Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.213Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.214Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.218Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.220Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.324Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.331Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.335Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.335Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:36.390Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.458Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.462Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:36.470Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.510Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.522Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.522Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:36.550Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:36.663Z
[PERFORMANCE]: Last frame took 54 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.755Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.759Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.761Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:36.770Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:36.824Z
[PERFORMANCE]: Last frame took 76 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.197Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.197Z
[PERFORMANCE]: Last frame took 67 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.281Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.282Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:40.291Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.304Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:41:40.485Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.521Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.569Z
[PERFORMANCE]: Last frame took 33 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/rnnoise-processor.min.js:1) wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/rnnoise-processor.min.js:1) falling back to ArrayBuffer instantiation
[PERFORMANCE]: Last frame took 47 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.947Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:40.948Z
qml: 'caller' is DEPRECATED. It has no effect.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:43.112Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:43.118Z
shm_open() failed: Permission denied
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:41:43.163Z
[PERFORMANCE]: Last frame took 41 ms to render.
[PERFORMANCE]: Last frame took 39 ms to render.
[PERFORMANCE]: Last frame took 54 ms to render.
[PERFORMANCE]: Last frame took 48 ms to render.
[PERFORMANCE]: Last frame took 34 ms to render.
[PERFORMANCE]: Last frame took 35 ms to render.
[PERFORMANCE]: Last frame took 34 ms to render.
[PERFORMANCE]: Last frame took 32 ms to render.
[PERFORMANCE]: Last frame took 32 ms to render.
[PERFORMANCE]: Last frame took 49 ms to render.
[PERFORMANCE]: Last frame took 34 ms to render.
[PERFORMANCE]: Last 10 frames took over 17 ms to render (last frame: 28 ms)
[PERFORMANCE]: Last frame took 32 ms to render.
[PERFORMANCE]: Last frame took 38 ms to render.
[PERFORMANCE]: Last 10 frames took over 17 ms to render (last frame: 23 ms)
[PERFORMANCE]: Last frame took 34 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:42:01.448Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:42:01.470Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:42:01.478Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:42:01.485Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.501Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.503Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.509Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.531Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.602Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.603Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.609Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:10) 2020-06-15T21:42:01.611Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/lib-jitsi-meet.min.js?v=4127.780:1) WebSocket connection to 'wss://meet.jit.si/xmpp-websocket?room=lalalalaldog' failed: Data frame received after close
[PERFORMANCE]: Last frame took 67 ms to render.
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:42:01.798Z
qml: [JS] (https://web-cdn.jitsi.net/meetjitsi_4180.838/libs/app.bundle.min.js?v=4127.780:72) 2020-06-15T21:42:01.873Z
[PERFORMANCE]: Last frame took 51 ms to render.
[PERFORMANCE]: Too many warnings were given. Performance monitoring stops.
qt.qpa.mirclient: Attempted to deliver an event to a non-existent window, ignoring.
qt.qpa.mirclient: Attempted to deliver an event to a non-existent window, ignoring.
[16420:16494:0615/234207.438433:ERROR:zygote_communication_linux.cc(208)] Failed to send Reap message to zygote`
