### ISSUE TITLE
Webber Webapp redirects to Morph Browser

### ISSUE THREAD

**Issue by polypode** [timsueberkrueb/webber#31]
System: FP2 running UbTouch OTA12 stable.

Observed issue: When opening a web app created with webber, the web app opens but redirects immediately to morphbrowser and opens the link in morphbrowser. The web app remains open but blank.

Expected behaviour: The link is opened in the web app. No additional web browser is opened.

**Comment by BigB84** [comment]
I had same problem with web app creator, I _solved_ that problem by pasting link dedicated for mobile sites e.g. with prefix "m" (mysite.com ==> m.mysite.com). Unfortunately this prefix is available and it works only for some sites. So You can check how site opens in other mobile device which should be recognized and rewrite it manually to webber/web app creator.

I don't know if it may be OS problem?

Could you give example of site?

**Comment by timsueberkrueb** [comment]
This can likely be solved by adding an url pattern:

1. Check which url gets opened in the webbrowser e.g. `https://exampleapp.com`
2. Open Webber and enter the original url of the site (e.g `https://example.com`) - or you can also try to just enter the url it redirected to, e.g. `https://exampleapp.com`
3. Go to `Customize > Url patterns` and add an additional pattern based on where the original site redirects to, e.g. `https://exampleapp.com/*` if the site redirets to `https://exampleapp.com/<something>`.

Url patterns control which urls get opened inside the apps and which get opened in the system browser. Webber adds `https?://example.com/*` and `https?://*.example.com/*` by default which is often enough. Some sites may require additional tweaking, though. You can read more about url patterns in [the url patterns docs](http://docs.ubports.com/en/latest/appdev/webapp/guide.html#url-patterns).

If that doesn't work, could you please provide the url of the site you experience this problem with? Thanks!

**Comment by timsueberkrueb** [comment]
Please reopen if you still experience this issue and if it cannot be solved by adding an url pattern/changing the url.

**Comment by Vistaus** [comment]
URL patterns do kind of fix it, but not always. For example, if I create a Duolingo webapp and add a Google URL pattern to be able to log in to Duolingo with my Google account, it redirects to Google within the app which is good (without the pattern, it would open Morph instead). However, after logging in to Google, it doesn't redirect me back to Duolingo meaning the login process didn't complete.

**Comment by timsueberkrueb** [comment]
@Vistaus you can try removing all url patterns. It should then open everything in the app. I plan to add a more intuitive option for that in the future.

**Comment by Vistaus** [comment]
@timsueberkrueb Thanks, I just tried that, but then it opens Morph again.

**Comment by timsueberkrueb** [comment]
Thanks, I will look into this next week, also.

**Comment by Vistaus** [comment]
Cool, thanks! :)
