### ISSUE TITLE
Improve icon finder

### ISSUE THREAD

**Issue by bhdouglass** [timsueberkrueb/webber#37]
It appears as if it's just the favicon that is being parsed for use as the app's image. Is there any way the web manifest or other icons (opengraph/apple) could be parse for a better option (If it's not doing that already)?

**Comment by timsueberkrueb** [comment]
Hey Brian, it's currently looking for the following patterns:
https://github.com/timsueberkrueb/webber/blob/master/src/core.rs#L52
Supporting the PWA manifest would be a great enhancement, though.

**Comment by bhdouglass** [comment]
Ok, cool, so is it using the apple icon or favicon first?

**Comment by timsueberkrueb** [comment]
It's currently using the favicon first, which is probably a mistake. It also ignores the sizes attribute. There is definitely some room for improvement here :)

**Comment by bhdouglass** [comment]
Ok, so I'm thinking maybe check if there is a manifest and parse that first for info. If no manifest, then check for and find the best apple icon, falling back to the opengraph icon, and finally using the favicon. What do you think?

**Comment by timsueberkrueb** [comment]
Sounds good :+1:

**Comment by timsueberkrueb** [comment]
This is now finally in progress. Initial PWA has been implemented.

TODO:

* [ ] OpenGraph icon
* [ ] Favicon
* [ ] Sort by icon size/icon type
* [ ] Allow user to pick any of the available icons

**Comment by timsueberkrueb** [comment]
Done.
