### ISSUE TITLE
The ceated app fails to install

### ISSUE THREAD

**Issue by 3arn0wl** [timsueberkrueb/webber#38]
Sorry to post a bug. (I think Webber's a great app)

I'm on dev channel.
Recently the app had been crashing after putting the URL of the website in.
The UBPorts forum suggested I downloaded https://github.com/timsueberkrueb/webber/releases/download/v0.4.0/webber.timsueberkrueb_0.4.0_armhf.click , which I did... And I presume it over-wrote the previous version?

Now the process seems to get as far as installing, but a popup says "Installation failed This package could not be installed. Make sure it is a valid click package."

**Comment by gbdomubpkm** [comment]
Don't forget that V.0.4.0 is an older version that has its own problems..

Which smartphone? [related to the developer WARNINGS (OpenStore) ]

Which site link for your webapp?

With V0.4.0, however, it MAY be that simply removing the special characters from the .click name will install the webapp...

**Comment by timsueberkrueb** [comment]
Should be fixed in `0.5.7`. Please let me know if the problem persists!

**Comment by 3arn0wl** [comment]
:) Thank you for your work on this...

The process seems to work now, but the created webapp doesn't show up in the homescreen. Sorry. :/

 3

On Thu, 10 Sep 2020 03:19:12 -0700, Tim wrote:
> Should be fixed in `0.5.7`. Please let me know if the problem persists!
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by timsueberkrueb** [comment]
@3arn0wl which device are you using?

**Comment by 3arn0wl** [comment]
Nexus5 on today's dev

On Thu, 10 Sep 2020 03:28:08 -0700, Tim wrote:
> @3arn0wl which device are you using?
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by timsueberkrueb** [comment]
I'm also using a Nexus 5 on dev (build number 2020-09-10/2) but it works for me.
Have you tried cleaning Webber's cache, restarting the device, or rebooting the device?
If that does not help, which website did you try to create a shortcut for? Thanks!

**Comment by 3arn0wl** [comment]
I will try that now! 

Thank you!!

On Thu, 10 Sep 2020 04:51:48 -0700, Tim wrote:
> I'm also using a Nexus 5 on dev (build number 2020-09-10/2) but 
> it works for me.
> Have you tried cleaning Webber's cache, reinstalling Webber, or 
> rebooting the device?
> If that does not help, which website did you try to create a 
> shortcut for? Thanks!
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by 3arn0wl** [comment]
Sorry to say: same thing happened. It does show up in UTTT...

I'm a little embarrased to admit it was a geocaching web page : https://www.geocaching.com/account/dashboard

I used the Share feature in Morph.

Your app does make making webapp really easy!

3


On Thu, 10 Sep 2020 04:51:48 -0700, Tim wrote:
> I'm also using a Nexus 5 on dev (build number 2020-09-10/2) but 
> it works for me.
> Have you tried cleaning Webber's cache, reinstalling Webber, or 
> rebooting the device?
> If that does not help, which website did you try to create a 
> shortcut for? Thanks!
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by 3arn0wl** [comment]
Hmm... I opened it using OpenStore, and now it shows up on my desktop.

A HUGE THANK YOU for all your work. It is much appreciated.

3

On Thu, 10 Sep 2020 04:51:48 -0700, Tim wrote:
> I'm also using a Nexus 5 on dev (build number 2020-09-10/2) but 
> it works for me.
> Have you tried cleaning Webber's cache, reinstalling Webber, or 
> rebooting the device?
> If that does not help, which website did you try to create a 
> shortcut for? Thanks!
>

-- 
Sent using Dekko from my Ubuntu device

**Comment by timsueberkrueb** [comment]
That's great, thanks!
