### ISSUE TITLE
Multiple Webber webapps on local server overwrite each other.

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [timsueberkrueb/webber#39]
Webber works perfectly except for one thing. I have a local server running multiple interfaces for different programs and you access them via different port numbers. Webber creates the first webapp perfectly and in some sense it creates the next ones perfectly too except it overwrites the first one and you only end up with one. It looks like while naming the app it strips off the port number and saves everything under the local ip address only.

Example Address: 192.168.1.100:8080
Resulting App points to 192.168.1.100:8080
App saved as 192-168-1-100.webber

Device: OnePlus One (Bacon)

OS: Ubuntu Touch 16.04(OTA-14)

Webber  0.5.7

**Comment by timsueberkrueb** [comment]
Thanks for reporting. You're correct, it currently ignores the port number when generating an app name.
