### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#4]
Thank you for this new and very useful application. I started promoting it.
Can you give permission to webapps to read  sounds? Because it seems impossible at the moment (music sites in streaming or videos...).
Thank you.

**Comment by gbdomubpkm** [comment]
Yes, permissions :

Also   Import data from other applications (file manager, gallery...) so that we can upload attachments. I tested with a webapp created with my email provider and to upload, I have no access to anything.

Also,   export to other applications? Is / will it be possible to download files with the webapps created?   Will the work done by Balcy on download for webapps in morph-browser be beneficial to you ? or the downloading of Webber webapps can / could work without it ?

**Comment by timsueberkrueb** [comment]
Done.
Import also works now in my tests, haven't tested the download future. If you test it, please report! Thanks!

**Comment by gbdomubpkm** [comment]
Tested with  OTA-11 :
   For sound of webapps, it's ok.
   For uploading it's ok.
   For downloading, it doesn't work for me with a  webapp done with my mail provider.

But downloading should be tested with a phone on dev channel so as to see if it's work.

F

**Comment by timsueberkrueb** [comment]
Ok, will test. What happens when you try to download something?

**Comment by gbdomubpkm** [comment]
In fact, when I try to download an attachment from an email by clicking on the attachment, nothing happens. The action is frozen, no window opens, no action and download progress in a directory is shown.

**Comment by timsueberkrueb** [comment]
I tested it on the Dev channel. Doesn't work with my email provider either. Does work perfectly fine with GitHub releases though. Most probably that's a limitation with/bug in `webapp-container`, then (https://github.com/ubports/morph-browser).

**Comment by gbdomubpkm** [comment]
This ? https://github.com/ubports/morph-browser/issues/254

**Comment by timsueberkrueb** [comment]
I don't know but I don't think that's related. Maybe we could ask one of the Morph developers on Telegram?

**Comment by gbdomubpkm** [comment]
See https://forums.ubports.com/topic/3415/download-in-for-webapps the thread open by me. If you want to use it.

**Comment by timsueberkrueb** [comment]
Yeah, will have to investigate what web API/method our email providers use to download stuff so we can create a reproducible case.

**Comment by gbdomubpkm** [comment]
Good news! At least on the dev channel. I advise you to try again. I hadn't been able to test a device in dev before. It works for me. The downloaded file is in.local/share/webapp.../Downloads. Seen with dev 407 for bq E 4.5.

**Comment by timsueberkrueb** [comment]
Interesting, thanks for the info!
