### ISSUE TITLE
 Feature request // option to disable images

### ISSUE THREAD

**Issue by Alaraajavamma** [timsueberkrueb/webber#41]
Feature request //
Option to disable images when browsing

Description of feature //
Option to not load images when browsing in Webapps
This would save lot of data + as bonus it wil make webapps much faster

**Comment by timsueberkrueb** [comment]
Hey @Alaraajavamma, thanks for the suggestion.
Webber creates shortcuts that run Morph Browser's [`webapp-container`](https://docs.ubports.com/en/latest/appdev/webapp/guide.html). Therefore, Webber has limited control over the web view that displays the webpage; in fact it is limited to the command line options provided by `webapp-container`. Hence, https://github.com/ubports/morph-browser/issues/443 has to be implemented first and exposed as a command line option in `webapp-container`. Once it's implemented, we can of course add it as an option to Webber!
