### ISSUE TITLE
When webapp has leading space(s) preceding the app name, the app will not appear in grid on UT

### ISSUE THREAD

**Issue by matv1** [timsueberkrueb/webber#43]
steps to reproduce:
create a webapp with webber for https://nos.nl/ (the public news site in the Netherlands)
leave everything as default (so also the suggested appname) and create the app.

the app will not appear in the app-grid. It will however show up in 'installed apps' in the open-store. It will appear right at the top of the list because instead of the appname, it will show some dots.

This is caused by the suggested (default) app name containing leading white spaces.
to confirm:
recreate the app but this time remove the entire suggested name INCLUDING the spaces. input some new name without spaces. Hit create again and the app will appear

Note: it can be debated that the cause of the app not showing in the app grid is not a webber issue at all but rather a lomiri bug: the appgrid seems to be sorted alphabetically and mabet not able to deal with charactars like space.. this is a hunch on my part though. Have not actually looked at the code.

But the issue may resolve a lot of reports about missing apps from webber in a simple way. All it probably needs is a trim() function.
As an addition, it may also be wise to limit the input length of the name. As you will see in the example, the default name can get very long

**Comment by timsueberkrueb** [comment]
Thank you for reporting, Webber should indeed trim whitespace.
