### ISSUE TITLE
[Feature request] Add the option to delete cache, config and shared files when closing

### ISSUE THREAD

**Issue by spartid** [timsueberkrueb/webber#44]
Hello,

First, thank you very much for this app, which helps greatly ! 
My request is the following : currently there is no option to delete cache, cookies and history in a webapp created with Webber. Keeping them can be useful, but it can also be a flaw regarding privacy. Currently, the only way to delete traces is to remove files in ~/.cache/www-your-web-app, ~/.config/www-your-web-app, and ~/.local/share/www-your-web-app with the terminal.

Could you add a possibility to delete those when the webapp closes ?

Yours sincerely,

spartid

**Comment by timsueberkrueb** [comment]
Hey, thanks for the proposal!

Webber creates shortcuts that run Morph Browser's [`webapp-container`](https://docs.ubports.com/en/latest/appdev/webapp/guide.html). Therefore, Webber has limited control over the web view that displays the webpage; in fact it is limited to the command line options provided by `webapp-container`.
Hence, this feature needs to be implemented in [Morph Browser](https://github.com/ubports/morph-browser) first before we can add it as an option to Webber.

`webapp-container` would have to expose a new command line option (e.g. `--disable-persistent-storage`) which would need to adjust the `QtWebEngine` profile used in the webview (e.g. by setting [`offTheRecord`](https://doc.qt.io/qt-5/qml-qtwebengine-webengineprofile.html#offTheRecord-prop)) similar to how it's done for the incognito mode of regular Morph Browser.

So I would recommend you to file this as a feature request for Morph browser.
