### ISSUE TITLE
Please allow editing the web address

### ISSUE THREAD

**Issue by ruedigerkupper** [timsueberkrueb/webber#45]
Whenever I share a page from Morph to Webber, Webber takes the current web address and does not allow editing it.

However, almost always Morph points to some very special subpage of the page I really want my web app to point at. I do not want my web app to land on that specific subpage every time I open it, instead I want to specify the generic web address.
Just imagine the web page changes its login process or redirection scheme. There is no guarantee that this particular subpage still exists tomorrow.
Please provide a way of editing the address shred from Morph.

**Comment by timsueberkrueb** [comment]
You definitely should be able to edit the web address using the text field at the very top of the screen after sharing from Morph. If that doesn't work, can you give more details what happens if you try to edit the url? Also which device are you using? Thanks!

**Comment by ruedigerkupper** [comment]
Oh no! I did not recognize this field at all. Stupid me. Everything's all right, thank you!
