### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by timsueberkrueb** [timsueberkrueb/webber#47]
Dear translators! A new release of Webber is coming soon including some new strings. 
If you have the time, please update your translations.
You could also test the [new release candidate](https://github.com/timsueberkrueb/webber/releases/tag/v0.6.0-rc.1) to see how the new strings are used. 
Thank you very much!

* [x] ar @herobrine7gamer
* [x] de @timsueberkrueb 
* [x] es @j2g2rp
* [x] fr @Anne017 
* [ ] it (via email by D'Antonio Giampietro)
* [x] nl @Vistaus 

If you don't want me to ping you in case of translation updates, please just leave a comment :)

**Comment by gbdomubpkm** [comment]
Hello @timsueberkrueb 
Can you update the app for the translations already done ? Thanks in advance.
