### ISSUE TITLE
Location not recognized

### ISSUE THREAD

**Issue by Vistaus** [timsueberkrueb/webber#53]
I have one web app which I granted the location permission. The first time it worked fine and it found my current location, but ever since, it's not looking for my location anymore. So it looks like location access is a bit buggy. uNav has no problem finding my location each time I open it, so it doesn't seem to be a UT bug.

**Comment by timsueberkrueb** [comment]
Hey, is this still a problem? In either case, that's likely an upstream issue with `webapp-container` (part of Morph Browser).

**Comment by Vistaus** [comment]
Hey! It is, but you're right: it's also an issue in Morph. I'm closing this, because it's something I need to report upstream.
