### ISSUE TITLE
Fail to create a webapp with cesoirtv.com site

### ISSUE THREAD

**Issue by gbdomubpkm** [timsueberkrueb/webber#56]
You can test. I fail to create a webapp for this site.
Can you ?
The website works well with morph-browser

![cesoirtv com webapp failed](https://user-images.githubusercontent.com/50362604/176208863-156f5c39-5526-46d5-aea7-35bc0da674b1.png)

**Comment by timsueberkrueb** [comment]
Sorry, the app is currently unmaintained. I don't know if/when I will get back to it. Contributions are always welcome; transfer of ownership is also possible.

**Comment by gbdomubpkm** [comment]
Shame. This extremely great app  is one of the most useful and thanks for all your work done on it.  Maybe you should post a message for info on the forum ?!

**Comment by gbdomubpkm** [comment]
I put the screenshot of your message on the forum:
https://forums.ubports.com/topic/7891/webapp-creator-webber/1

**Comment by gbdomubpkm** [comment]
Hello @JamiKettunen . Do you have an idea about this issue that i have on 16.04 ? I can't test on 20.04 as i am yet on 16.04.

**Comment by timsueberkrueb** [comment]
The site is stuck in a redirect loop:

```
https://www.cesoirtv.com/
https://consents.prismamedia.com/v2?redirectUrl=https%3a%2f%2fconsents.cesoirtv.com%2fv2%3fredirectUrl%3dhttps%253a%252f%252fwww.cesoirtv.com%252f
https://consents.cesoirtv.com/v2?redirectUrl=https%3a%2f%2fwww.cesoirtv.com%2f&authId=1cf7f36dd3ce29b6903f03f62e00b8a0&fromStep=v2-site1.1-step1
https://www.cesoirtv.com/
https://consents.prismamedia.com/v2?redirectUrl=https%3a%2f%2fconsents.cesoirtv.com%2fv2%3fredirectUrl%3dhttps%253a%252f%252fwww.cesoirtv.com%252f
https://consents.cesoirtv.com/v2?redirectUrl=https%3a%2f%2fwww.cesoirtv.com%2f&authId=2974110fd0505502b3f94b794c9a4b43&fromStep=v2-site1.1-step1
https://www.cesoirtv.com/
...
```
This is because it is trying to set a cookie, and redirects if it does not find the cookie.
It should work with the following click package (for xenial):

[webber.timsueberkrueb_0.6.2_arm64.zip](https://github.com/timsueberkrueb/webber/files/12105581/webber.timsueberkrueb_0.6.2_arm64.zip)

**and** if you configure `https?://*.prismamedia.com/*` as an additional url pattern when creating the web app.

**Comment by gbdomubpkm** [comment]
Hello.

Thanks for looking into the issue.

So it doesn't work for me with v 0.6.2 and the described procedure (screen remains blank when launching the webapp). Does it work for you ?

However with v0.6.0-rc.1 and ignoring the redirect error message in red, I can finally create the cesoirtv webapp. On the other hand, I am obliged to accept cookies, I would have liked to block the acceptance window.

Regards

**Comment by gbdomubpkm** [comment]
Hello !
Now, i'm on focal and i get a fully blank page with the https://www.cesoirtv.com new shortcut.
It's ok using morph-browser.

**Comment by gbdomubpkm** [comment]
Solved : two patterns added:
`https?://*.cesoirtv.com/*`
`https?://*.prismamedia.com/*`
