### ISSUE TITLE
[Feature request] Share button

### ISSUE THREAD

**Issue by Philippe117** [timsueberkrueb/webber#58]
# Introduction
Hi,

First, I want to thank you for making this app. I love how it can turn any webpage into a safe and efficient webapp.
I'm currently using it a lot on my Volla22 and I believe it is a life saver for the whole Ubuntu touch workflow.
There is just one this that is missing in this app for me. A share button.

# Justification
I have a kodi based media center at home to which I can send youtube videos by using the share button from the Morph browser.
However, youtube if very slow on Morph because of all the ads and trackers.
It is also less convenient to use than a dedicated app.
Webber can control which urls are allowed by the app. Effectively making it super fast and efficient.
This is why I would like to see a share button on webber. To get the best of both worlds.

# Desired behavior

## When creating the app
In the controls section, there would be one more option.

- [x] Don't show a title bar
- [x] Show the title bar
- [x] Show the title bar with back/forward buttons
- [ ] Show the title bar with back/forward and share buttons   <-- This is the new option

## When using the app
If the new option is enabled, a share button is displayed beside the title bar.
Clicking on it would popup the same menu as Morph's share button.

## Note
I will try to implement it on my own but I first need to learn rust and a lot of other things. So a bit of help would be highly appreciated.

What do you think?

**Comment by timsueberkrueb** [comment]
Hey @Philippe117, happy to hear you're interested in trying to implement this feature!

Webber creates a `click` app which executes `webapp-container` which [is part of Morph Browser](https://gitlab.com/ubports/development/core/morph-browser/-/tree/main/src/app/webcontainer). I.e., Webber can only support options supported by Morph Browser's `webapp-container` (see [currently supported options](https://gitlab.com/ubports/development/core/morph-browser/-/blob/main/src/app/webcontainer/webapp-container.cpp#L297)).
Hence, this feature would have to be implemented in `webapp-container` first. You can also request it by opening an issue there or let them know you would like to implement it (it might be worth to ask for advice in the app dev group on Telegram).

Once `webapp-container` supports this, it should be fairly straightforward to add the option to Webber:

* In Rust, add an option to [`AppModel`](https://github.com/timsueberkrueb/webber/blob/master/src/model.rs#L144) similar to `enableBackForward` and adjust all places where `enableBackForward`/`enable_back_forward` is read to also handle the new option
* In QML, add an option to [`OptionalSettings`](https://github.com/timsueberkrueb/webber/blob/master/qml/OptionalSettings.qml#L15) 
* In QML, connect these two in [`AddPage`](https://github.com/timsueberkrueb/webber/blob/master/qml/AddPage.qml#L313)

**Comment by Philippe117** [comment]
Thank you @timsueberkrueb. This is the kind of information I needed. I'll see what I can do to get the share function on the webapp-container. I'll start by opening an issue on their gitlab. Thanks again.

**Comment by gbdomubpkm** [comment]
> I'm currently using it a lot on my Volla22 and I believe it is a life saver for the whole Ubuntu touch workflow.

Although there is no maintenance on the agenda alas, I'm at least glad to read that the essential Webber is working - will still work with halium 11 / ubuntu 20.04.
