### ISSUE TITLE
Can't make webapp for personalised BBC News Website

### ISSUE THREAD

**Issue by dtarrant2019** [timsueberkrueb/webber#60]
In the past I made a click package for the BBC News website using webapp-creator. It was personalised for me so that I stayed logged in and got local news and weather. I just clicked the webapp icon and it worked on my Nexus-4 and my BQ M10 Tab. But now it's broken. It was of no value to anyone but me.

I have a morph bookmark which works, but that's not so slick as clicking a webapp icon. I've tried using webber to make a new webapp from my bookmark, but the webapp doesn't work.

PS. My original webapp is still working working ok on my Pinephone. (click made with webapp-creator)

**Comment by gbdomubpkm** [comment]
It should work. Don't forget to enable 'do not suspend app' of the BBC shortcut with UTTT.

**Comment by dtarrant2019** [comment]
So I tried enabling 'do not suspend app' of the BBC shortcut with UTTT as suggested. It certainly worked much better than previously. The webapp opened, but not with me already logged in to my personalised BBC News version. Also, the webapp displayed options to log in or register, but they didn't work. My conclusion is that the BBC News website is too convoluted and it's unreasonable to expect Webber to handle it.

The event that caused my previous clicks to break was the upgrade to OTA-24. I wonder if I made a new click with webapp-creator I would have more success?

**Comment by gbdomubpkm** [comment]
I have no personalised BBC account. I don't know in this case. I only made a shortcut with BBC radio and it work well. In some webapps done with webber, i can stay logged to my account all the time or only a certain time. It depends of cookies of the website i think.

**Comment by dtarrant2019** [comment]
I tried using webapp-creator and it reported click succesfully created. But when I looked in .cache>webapp-creator.jujuyeh, it wasn't there. However, the previous clicks I made were still all present.
Conclusion: BBC News website is too difficult. Don't waste any more time. Anyhow many thanks for your suggestions.

**Comment by dtarrant2019** [comment]
Well, I guess it's time to close the issue.
