### ISSUE TITLE
pleaseeeee some one get this going in 20.4 

### ISSUE THREAD

**Issue by raresoupninja** [timsueberkrueb/webber#65]
i slapped the newest vertion of ubports on my pixel 3a and the webber app wasnt there the other missing apps are sad but webber is key pleaseeeeeeeee port it over to the 20,4

**Comment by timsueberkrueb** [comment]
Hey, I have uploaded a build for `20.04` for `armhf` and `arm64` to the Open Store.
Do I understand correctly that you cannot find the app in the Open Store on your device with `20.04`?
CC: @JamiKettunen

**Comment by JamiKettunen** [comment]
@raresoupninja Seems available to me on 20.04 when I search for it on OpenStore app on both a Volla Phone and Fairphone 4. Does it not appear at all when you search? Are you on 20.04 Release Candidate or Development update channel?
<img src="https://user-images.githubusercontent.com/47358222/218484065-3a7ddb27-29e3-4567-917e-cdf95cec4df6.png" width="240" />

**Comment by JamiKettunen** [comment]
Looking at https://open-store.io/app/webber.timsueberkrueb the downloads indeed are available, considering the lack of response (and the fact I've been able to find this just fine on an `arm64`  device) I think this issue can be closed
![image](https://user-images.githubusercontent.com/47358222/224051493-22260b73-b147-4884-83c1-a58be336dd27.png)

**Comment by raresoupninja** [comment]
Yes I have since gotten it aswell
