### ISSUE TITLE
Application crash on startup (Vollaphone 22 and build Focal)

### ISSUE THREAD

**Issue by SunSemillia** [timsueberkrueb/webber#67]
Hello,

Webber application crash on startup on my Vollaphone 22 with Focal Build.
It worked like a charm on Xenial build, but don't with Focal build.

I tried to launch it with cmd line or debug and I get a Segmentation Fault.

When I launch it with app drawer with the shortcut, I can see these logs in journalctl.
We can see 'AVC apparmor="DENIED"' maybe the root cause ?

```
Apr 23 19:57:20 ubuntu-phablet systemd[2035]: Started lomiri-app-launch--application-click--webber.timsueberkrueb_webber_0.6.0--.service.
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.068] qtmir.mir: SessionAuthorizer::connection_is_allowed - this= qtmir::SessionAuthorizer(0x7f7c1bbed0) pid= 3>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.103] qtmir.sessions: Wakelock acquired "11"
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.112] qtmir.mir: SessionAuthorizer::configure_input_is_allowed - this= qtmir::SessionAuthorizer(0x7f7c1bbed0) p>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.113] qtmir.mir: SessionAuthorizer::set_base_input_configuration_is_allowed - this= qtmir::SessionAuthorizer(0x>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.113] qtmir.mir: SessionAuthorizer::configure_display_is_allowed - this= qtmir::SessionAuthorizer(0x7f7c1bbed0)>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.113] qtmir.mir: SessionAuthorizer::set_base_display_configuration_is_allowed - this= qtmir::SessionAuthorizer(>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.113] qtmir.mir: SessionAuthorizer::screencast_is_allowed - this= qtmir::SessionAuthorizer(0x7f7c1bbed0) pid= 3>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.113] qtmir.mir: SessionAuthorizer::prompt_session_is_allowed - this= qtmir::SessionAuthorizer(0x7f7c1bbed0) pi>
Apr 23 19:57:21 ubuntu-phablet .(1)[1039:init]init: sys_prop: invalid command 2
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.138] qtmir.sessions: TaskController::onSessionStarting - sessionName=webber
Apr 23 19:57:21 ubuntu-phablet audit[3446]: AVC apparmor="DENIED" operation="open" profile="webber.timsueberkrueb_webber_0.6.0" name="/sys/kernel/tracing/trace_marker" pid=3446>
Apr 23 19:57:21 ubuntu-phablet kernel: -(0)[183:kauditd]kauditd_printk_skb: 19 callbacks suppressed
Apr 23 19:57:21 ubuntu-phablet kernel: .(0)[183:kauditd]audit: type=1400 audit(1682272641.204:211): apparmor="DENIED" operation="open" profile="webber.timsueberkrueb_webber_0.6>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.222] qtmir.sessions: TaskController::onSessionStopping - sessionName=webber
Apr 23 19:57:21 ubuntu-phablet systemd[2035]: lomiri-app-launch--application-click--webber.timsueberkrueb_webber_0.6.0--.service: Main process exited, code=killed, status=11/SE>
Apr 23 19:57:21 ubuntu-phablet systemd[2035]: lomiri-app-launch--application-click--webber.timsueberkrueb_webber_0.6.0--.service: Failed with result 'signal'.
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.230] file:///usr/share/lomiri//Stage/Stage.qml:161: TypeError: Type error
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: Unable to reset failed unit: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit lomiri-app-launch--application-click--webber.tim>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.233] qtmir.sessions: Wakelock released "11"
Apr 23 19:57:21 ubuntu-phablet repowerd[1406]: LogindSessionTracker: dbus_get_session_by_pid() failed: GDBus.Error:org.freedesktop.login1.NoSessionForPID: PID 2747 does not bel>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.262] ApplicationManager::onProcessFailed - upstart reports failure of application "webber.timsueberkrueb_webbe>
Apr 23 19:57:21 ubuntu-phablet lomiri[2747]: [2023-04-23:19:57:21.263] ApplicationManager::onProcessStopped reports stop of appId= "webber.timsueberkrueb_webber" which AppMan i>
```

I tried to install a personal build from git clone this repo and I tried to install a click package download from app store, but it's the same result.
Any idea of what goes wrong ?

Thank for this app !

**Comment by boroli** [comment]
Same here. Neither opening Webber itself works, nor selecting Webber while "Share" the site.

I get similar error messages on the same phone with the same build.

**Comment by timsueberkrueb** [comment]
@JamiKettunen hey, if you have the time, do you have an idea what might be going on here?

**Comment by Vistaus** [comment]
Same on Redmi 9 with Xenial. At first, it opened but didn't make usable webapps (see my other issue on here), but at the moment it doesn't even launch Webber at all.

**Comment by JamiKettunen** [comment]
@timsueberkrueb While I can reproduce this issue on my end as well it appears to be related to the `.click` uploaded to OpenStore (https://open-store.io/api/v3/apps/webber.timsueberkrueb/download/focal/arm64/0.6.0) being potentially broken somehow, as running `clickable build -a arm64` myself locally and installing the created `build/aarch64-linux-gnu/app/webber.timsueberkrueb_0.6.0_arm64.click` it immediately launches just fine... anything I can do to help?

For reference here's the one I built myself: [webber.timsueberkrueb_0.6.0_arm64.click.zip](https://github.com/timsueberkrueb/webber/files/12035791/webber.timsueberkrueb_0.6.0_arm64.click.zip) (stupid gh made me zip it)

**Comment by timsueberkrueb** [comment]
Thanks! I tried to flash focal on my Sony Xperia X F5121, but it failed (stuck in recovery). I will try to get it to work, but if you send me a working `.click` with the version bumped to `0.6.1` in the meantime, I will just upload it to the Open Store.

**Comment by Vistaus** [comment]
> @timsueberkrueb While I can reproduce this issue on my end as well it appears to be related to the `.click` uploaded to OpenStore (https://open-store.io/api/v3/apps/webber.timsueberkrueb/download/focal/arm64/0.6.0) being potentially broken somehow, as running `clickable build -a arm64` myself locally and installing the created `build/aarch64-linux-gnu/app/webber.timsueberkrueb_0.6.0_[arm64.click](http://arm64.click)` it immediately launches just fine... anything I can do to help?
> 
> For reference here's the one I built myself: [webber.timsueberkrueb_0.6.0_arm64.click.zip](https://github.com/timsueberkrueb/webber/files/12035791/webber.timsueberkrueb_0.6.0_arm64.click.zip) (stupid gh made me zip it)

Not able to install this on Xenial.

**Comment by JamiKettunen** [comment]
@timsueberkrueb [webber.timsueberkrueb_0.6.1_arm64.click.zip](https://github.com/timsueberkrueb/webber/files/12064277/webber.timsueberkrueb_0.6.1_arm64.click.zip)


@Vistaus Well yeah it's a build for 20.04, you can't use it on 16.04; I could maybe build one for xenial as well with the breaking 20.04 related commits reverted from `master`

**Comment by Vistaus** [comment]
@JamiKettunen That would be very helpful as Webber is still broken on 16.04. It's the exact same issue as in the OP, just on 16.04. It would be fantastic if you could make a 16.04 build for me! 🙂

**Comment by JamiKettunen** [comment]
No idea if it works but here's a 16.04 build [webber.timsueberkrueb_0.5.8_arm64.click.zip](https://github.com/timsueberkrueb/webber/files/12064505/webber.timsueberkrueb_0.5.8_arm64.click.zip)

**Comment by Vistaus** [comment]
> No idea if it works but here's a 16.04 build [webber.timsueberkrueb_0.5.8_arm64.click.zip](https://github.com/timsueberkrueb/webber/files/12064505/webber.timsueberkrueb_0.5.8_arm64.click.zip)

Thanks! Translations are missing, not a big deal, but got a little further otherwise: Webber starts again and I can create a webapp again, but webapps still crash after installing. So back to my other issue… #40

**Comment by timsueberkrueb** [comment]
@JamiKettunen thank you, I've uploaded the package to the Open Store. I haven't yet succeeded in flashing focal on my device (xenial works).

**Comment by boroli** [comment]
Thanks. After update to the new version from the Open Store, this bug is resolved for me.
Could be closed.
