### ISSUE TITLE
Is it possible to include the ability to perform notifications?

### ISSUE THREAD

**Issue by Haidafraid** [timsueberkrueb/webber#69]
Hi there and thank you for this great app!
I used your app to create a webapp for a second homeserver of matrix that hosts the cinny webapp. Everything works just fine. Alas there is no notification of any kind if I get a new message. Is there a way to implement pushnotifications for webapps?
Or is there anyhow another way to make them work for an app created by webber?
The only thing I found was this:
`https://docs.ubports.com/en/latest/appdev/guides/pushnotifications.html` But to be honest, it did not help me much.

My Device is a vollaPhone x23 and I am using 20.04. (as of today the release candidate Version 113)
As I am pretty new in the issue business… and I do not think it is an issue at all - more some sort of feature request, but I did not know how to file that… there is the strong feeling I might have had to come up with more information of any kind. Please let me know if there is any further information you probably need from me and I will gladly post them here.
Thank you in advance for thinking about my little problem here.
Cheers Marc

**Comment by timsueberkrueb** [comment]
Hi Marc, it's all right. On GitHub, issues are used for feature requests as well as bug reports.
Webber basically creates a shortcut (`.desktop` file) which runs an application called `webapp-container` which is part of Morph Browser. Therefore, notification support would need to be implemented in Morph Browser, not in Webber. 
There have been suggestions to implement notifications support in morph browser but I'm not sure what the status is at the moment. If anyone is interested in joining the effort, a good place to ask would be the [Ubuntu touch app developers group](https://t.me/UbuntuAppDevEN) on Telegram.
