### ISSUE TITLE
[feature request] open local files possible?

### ISSUE THREAD

**Issue by uwahl** [timsueberkrueb/webber#70]
Is it possible to open local files either in documents or download folder?
In the moment the program refuses, i.e. is not acknowledged as a "nomal" URI...

**Comment by timsueberkrueb** [comment]
I see. You could maybe try an url of the form `file:///path/to/your/file` for a file named `/path/to/your/file`. However, note that the generated shortcuts are Ubuntu touch applications which are confined/sandboxed: they do not have access to arbitrary files. They do have access to certain directories, though, thus if you move the local files into a directory the app has access to, it may work.

See [this page on the Ubports documentation](https://docs.ubports.com/en/latest/appdev/guides/writeable-dirs.html) for the app directories. To find the application name, try something like `ls /home/phablet/.cache | grep webber`.

**Comment by uwahl** [comment]
Thank you for the advice, but Webber refuses to create a shortcut. It stops the process with a DNS-error message and doesn't accept the local file address of the type file:///path/to/your/file. Webber seems to wait for a real URI. By the way, Morph itself opens the very same local address file (inside of the allowed Downloads-folder) without any problem.

**Comment by timsueberkrueb** [comment]
Okay. To implement this feature, one would need to check if the provided string is a `file://` uri (or alternatively, if it is an invalid url, check if it is a valid path). Additionally, one could add the option for shortcuts to access certain directories (e.g. the Downloads folder) because by default they do not have access beyond [the default ones](https://docs.ubports.com/en/latest/appdev/guides/writeable-dirs.html).

**Comment by uwahl** [comment]
Yes, it would be helpful to implement accessing the Morph standard folder /home/phablet/Downloads
for a file of the type  file:///home/phablet/myfile
which can be opened flawlessly by Morph (e.g .txt, .html, .jpg,. png or .jpg files)

Am Sun, 13 Aug 2023 00:10:45 -0700, Tim Süberkrüb schrieb:
> Okay. To implement this feature, one would need to check if the 
> provided string is a `file://` uri (or alternatively, if it is 
> an invalid url, check if it is a valid path). Additionally, one 
> could add the option for shortcuts to access certain directories 
> (e.g. the Downloads folder) because by default they do not have 
> access beyond [the default 
> ones](https://docs.ubports.com/en/latest/appdev/guides/writeable-dirs.html).
>

--

**Comment by uwahl** [comment]
...local files still not allowed. Webber comment:..“URL scheme ist not allowed“...

**Comment by uwahl** [comment]
Any progress since to open local files...?
Thanks a lot for your work!  🙂
