### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by NotANewNick** [timsueberkrueb/webber#73]
A function I am missing is the ability to keep the webapp running in the background even when the screen is off.
If this was an available option when adding the webapp then any page that streams audio/video could be listened to even with the screen being off.
As it is now the audio stops as soon as the app doesn't have focus, making it impossible to create webapps from the most popular websites.

This function would take Ubuntu Touch significantly closer to not needing Android/iOS for anything.

**Comment by timsueberkrueb** [comment]
You can allow webapps to run in the background by activating the "prevent app suspension" option in the UT tweak tools app (https://open-store.io/app/ut-tweak-tool.sverzegnassi).

**Comment by NotANewNick** [comment]
UT Tweak Tool isnt available for 20.04 and UT Tweak Tool almost seems abandoned.
